---
- hosts: dbc-primary:dbc-replica:dbc-pgpool:application
  sudo:  true
  roles:
    - init
- hosts: dbc-primary:dbc-replica
  sudo:  true
  roles:
    - postgres
- hosts: dbc-replica
  sudo:  true
  roles:
    - postgres-streaming
- hosts: dbc-pgpool
  sudo:  true
  roles:
    - pgpool2
- hosts: application
  sudo:  true
  roles:
    - postgres-client
    - nodejs
    - ghostapp
    - nginx
