---
  - name: Create htpasswd file
    sudo: yes
    htpasswd:
      path: /etc/nginx/htpasswd.users
      name: kibana
      password: kibana
      owner: root
      group: www-data
      mode: 0640

  - name: Remove default config
    sudo: yes
    file:
      dest: /etc/nginx/sites-enabled/default
      state: absent

  - name: Add proxy to kibana
    sudo: yes
    template:
      src: kibana.conf.j2
      dest: /etc/nginx/sites-available/kibana.conf

  - name: Symlink kibana conf to enabled sites
    sudo: yes
    file:
      src: /etc/nginx/sites-available/kibana.conf
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: Restart nginx
    sudo: yes
    service:
      name: nginx
      state: restarted
