---
  - name: Check if recovery.conf file exists
    sudo: yes
    stat:
      path: "/etc/postgresql/{{ postgresql_version }}/main/recovery.conf"
    register: recovery_file

  - name: Stop tomcat7
    sudo: yes
    service:
      name: postgresql
      state: stopped

  - name: Remove current main files
    sudo: yes
    sudo_user: postgres
    command: "rm -rf /var/lib/postgresql/{{ postgresql_version }}/main"
    when: recovery_file.stat.exists == False

  - name: Create pgpass file
    sudo: yes
    sudo_user: postgres
    template:
      src: pgpass.j2
      dest: "/var/lib/postgresql/.pgpass"
      mode: 0600
    when: recovery_file.stat.exists == False

  - name: Start sync
    sudo: yes
    sudo_user: postgres
    shell: "pg_basebackup -h {{ postgresql_replication_ip }} -D /var/lib/postgresql/{{ postgresql_version }}/main -U {{ postgresql_replication_user }}  -X stream -v -P -w"
    when: recovery_file.stat.exists == False

  - name: Create recovery configuration
    sudo: yes
    template:
      src: recovery.conf.j2
      dest: "/etc/postgresql/{{ postgresql_version }}/main/recovery.conf"

  - name: Start postgres
    sudo: yes
    service:
      name: postgresql
      state: started
