---
  - name: Add Logstash repo key
    sudo: yes
    shell: "wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -"

  - name: Create Logstash repo
    sudo: yes
    lineinfile:
      dest: /etc/apt/sources.list.d/logstash-server.list
      line: 'deb http://packages.elasticsearch.org/logstash/{{ logstash_server_version }}/debian stable main'
      create: yes

  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install logstash
    sudo: yes
    apt:  pkg={{ item }} state=latest force=yes
    with_items:
      - logstash

  - name: Create logstash patterns directory
    sudo: yes
    file:
      path: "/opt/logstash/patterns"
      state: directory
      follow: yes

  - name: Add nginx access pattern conf
    sudo: yes
    template:
      src: nginx-pattern.j2
      dest: /opt/logstash/patterns/nginx
      owner: logstash
      group: logstash

  - name: Create certs directory
    sudo: yes
    file:
      path: "{{ logstash_server_ssl_cert_dir }}"
      state: directory
      follow: yes

  - name: Create private directory
    sudo: yes
    file:
      path: "{{ logstash_server_private_key_dir }}"
      state: directory
      follow: yes

  - name: Set openssl alt name to private ip
    sudo: yes
    lineinfile:
      dest: /etc/ssl/openssl.cnf
      line: "subjectAltName=IP:{{ ansible_all_ipv4_addresses[-1] }}"
      insertafter: 'v3_ca'

  - name: Create cert and key
    sudo: yes
    shell: "openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout {{ logstash_server_private_key_dir }}/logstash-forwarder.key -out {{ logstash_server_ssl_cert_dir }}/logstash-forwarder.crt"
    args:
      creates: "{{ logstash_server_ssl_cert_dir}}/logstash-forwarder.crt"

  - name: Copy cert locally
    fetch:
      src: "{{ logstash_server_ssl_cert_dir }}/logstash-forwarder.crt"
      dest: /tmp/logstash-forwarder.crt
      flat: yes

  - name: Add lumberjack input conf
    sudo: yes
    template:
      src: 01-lumberjack-input.conf.j2
      dest: /etc/logstash/conf.d/01-lumberjack-input.conf
      mode: 0644

  - name: Add syslog filter conf
    sudo: yes
    template:
      src: 10-syslog.conf.j2
      dest: /etc/logstash/conf.d/10-syslog.conf
      mode: 0644

  - name: Add nginx filter conf
    sudo: yes
    template:
      src: 20-nginx.conf.j2
      dest: /etc/logstash/conf.d/20-nginx.conf
      mode: 0644

  - name: Add lumberjack output conf
    sudo: yes
    template:
      src: 30-lumberjack.conf.j2
      dest: /etc/logstash/conf.d/30-lumberjack.conf
      mode: 0644

  - name: Restart logstash server
    sudo: yes
    service:
      name: logstash
      state: restarted
