---
  - name: Set up default encoding to utf8
    sudo: yes
    command: locale-gen en_US.UTF-8

  - name: Update locale for postgres
    sudo: yes
    command: update-locale LANG=en_US.UTF-8

  - name: Install PostgreSQL
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: create users
    sudo: yes
    sudo_user: postgres
    postgresql_user:
      name: "{{ item.name }}"
      password: "{{ item.pass }}"
      role_attr_flags: "{{ item.priv }}"
    with_items: postgresql_users

  - name: ensure databases are created
    sudo: yes
    sudo_user: postgres
    postgresql_db:
      name: "{{ item.name }}"
      owner: "{{ item.owner }}"
    with_items: postgresql_databases

  - name: Update postgresql conf
    sudo: yes
    template:
      src: postgresql.conf.j2
      dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"

  - name: Update postgresql access control
    sudo: yes
    template:
      src: pg_hba.conf.j2
      dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"

  - name: Restart tomcat7
    sudo: yes
    service:
      name: postgresql
      state: restarted
