---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - build-essential
      - python-software-properties
      - vim
      - curl
      - wget
      - mcrypt
      - git-core
      - git
      - zip
      - golang

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes
