---
  - name: Create project directory
    sudo: yes
    file:
      path: "{{ ghostapp_dir }}"
      state: directory

  - name: Get ghost
    sudo: yes
    get_url:
      url: https://ghost.org/zip/ghost-latest.zip
      dest: "{{ ghostapp_dir }}/ghost.zip"

  - name: Pause for 10 seconds
    pause:
      seconds: 10

- name: Unarchive Ghost
    sudo: yes
    unarchive:
      src: "{{ ghostapp_dir }}/ghost.zip"
      dest: "{{ ghostapp_dir }}/ghost"
